"""empty message

Revision ID: 1d002403c68f
Revises: 387a8703d84b
Create Date: 2025-03-16 14:22:14.621418

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d002403c68f'
down_revision: Union[str, None] = '387a8703d84b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("unique_biometrics", 'biometrics', ['user_id'])
    op.drop_constraint('payments_sub_id_fkey', 'payments', type_='foreignkey')
    op.create_foreign_key("payment_sub_link", 'payments', 'subscriptions', ['sub_id'], ['user_id'], ondelete='SET NULL')
    op.create_unique_constraint("unique_sub", 'subscriptions', ['user_id'])
    op.create_unique_constraint("unique_telegram_id", 'users', ['telegram_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("unique_telegram_id", 'users', type_='unique')
    op.drop_constraint("unique_sub", 'subscriptions', type_='unique')
    op.drop_constraint("payment_sub_link", 'payments', type_='foreignkey')
    op.create_foreign_key('payments_sub_id_fkey', 'payments', 'subscriptions', ['sub_id'], ['user_id'], ondelete='CASCADE')
    op.drop_constraint("unique_biometrics", 'biometrics', type_='unique')
    # ### end Alembic commands ###
