"""Reniew user model

Revision ID: 3a7209d8dc54
Revises: 117fd14ee478
Create Date: 2025-02-08 14:28:58.599169

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "3a7209d8dc54"
down_revision: Union[str, None] = "117fd14ee478"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("biomterics_user_id", "biometrics", ["user_id"])
    op.create_unique_constraint("sub_user_id", "subscriptions", ["user_id"])
    op.create_unique_constraint("unique_id", "users", ["telegram_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("biomterics_user_id", "users", type_="unique")
    op.drop_constraint("sub_user_id", "subscriptions", type_="unique")
    op.drop_constraint("unique_id", "biometrics", type_="unique")
    # ### end Alembic commands ###
