"""empty message

Revision ID: d153e88f06d4
Revises: 4af474d781b3
Create Date: 2025-03-22 17:34:42.546860

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd153e88f06d4'
down_revision: Union[str, None] = '4af474d781b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('start_workouts',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('day_number', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('day_number')
    )
    op.add_column('subscriptions', sa.Column('start_program_begin_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscriptions', 'start_program_begin_date')
    op.drop_table('start_workouts')
    # ### end Alembic commands ###
