name: "progress-project-bot"

services:

  postgres:
    image: postgres:16-alpine
    restart: "no"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: progress_db
    volumes:
      - "dev_database:/var/lib/postgresql/dev_data"

volumes:
  dev_database:
